### ISSUE TITLE
Is stream_framework a standalone or it uses django app.

### ISSUE THREAD

**Issue by X17** [tbarbugli/stream_framework_example#10]
i am new to this, can you guide me on deployment to aws ec2.
Does this example have celery to a-sync job?

**Comment by tbarbugli** [comment]
it would be great if you could give some more information of what you want to build and what your current application looks like. this way we can give you bit more detailed suggestions for your case.

**Comment by X17** [comment]
Our current webapp is written in php, now we are adopting service oriented architecture to power web and mobile apps.

we can use twitter style feed as separate unit using stream framework, but need to confirm the dependency. Is it standalone or we library for django framwork.

**Comment by tbarbugli** [comment]
stream_framework is not a standalone program but a library to build
activity streams and news feeds. If you are not familiar with the Celery
stack and don't have an existing infrastructure (eg. Redis/Cassandra and
RabbitMq) I suggest you to have a look at getstream.io, a hosted API
service built on top of stream_framework.

**Comment by X17** [comment]
@tbarbugli 
found this in django packages. https://www.djangopackages.com/packages/p/stream-framework/
Is it compatible with python 3 as it showing red mark for production / stable.

**Comment by tbarbugli** [comment]
unfortunately not yet, one of our dependencies (cqlengine) does not support python 3. If you are not going use Cassandra it should be trivial to run on Python 3. The package is stable and used in production by many users (authors included)

**Comment by X17** [comment]
@tbarbugli  we are currently using Redis as suggested by Thierry. Actually, we are experimenting in order to learn the SOA and thought building a independent feed system would align with our goal. In my understanding , We need 

> django > stream_framework 
> django - celery > rabbitmq
> redis

**Comment by X17** [comment]
@tbarbugli  lastly, is it the same project you're using at getstream.io or the advanced / modified version of it.

**Comment by tbarbugli** [comment]
at getstream.io we use the version of stream_framework published on PyPI

**Comment by X17** [comment]
@tbarbugli https://github.com/tbarbugli/stream_framework_example/blob/master/requirements/base.txt
i couldn't find rabbitmq as dependency.

**Comment by tbarbugli** [comment]
you are looking at python requirements. RabbitMQ is not a library, but a server you should install and configure in order for Celery to store fanout tasks. During development you can use celery without rabbitmq with the CELERY_ALWAYS_EAGER setting.

**Comment by X17** [comment]
thanks a lot for insight. i will setup the app and will ping you if run into trouble. 

PS: will definitely try getstream.io and let my friends know about the seamless service.

**Comment by X17** [comment]
@tbarbugli quick performance insight.

we are using stream framework for two verbs : follow user & favorite item
The activity feed gets generated as soon as the user logs into dashboard based on timestamp, we are not much concerned with notification system. How much stability can we achieve on stream framework. Any recommendation on the configuration side to increase performance.

**Comment by tbarbugli** [comment]
stream framework and the server components used (redis/cassandra, celery, rabbitmq) are battled tested, you should not expect stability problems from them.

**Comment by X17** [comment]
@tbarbugli  How much scalable is it, users ? will give us timeline to build upgrade or switch to service.

**Comment by X17** [comment]
@tbarbugli  Is there any inbuiilt api to the framework for this example to retrieve data in json/xml.

**Comment by tbarbugli** [comment]
no it is up to the user to decide how to interface feeds. For this I suggest you to look at django restful framework.

**Comment by X17** [comment]
@tbarbugli  where does the fixtures loads the samples data. as i am unable to view in sqlite.

**Comment by tbarbugli** [comment]
fixtures are defined in core/fixtures, for sake of simplicity we embedded a ready sqlite db in the repo

**Comment by X17** [comment]
@tbarbugli any issues while upgrading Django==1.5.5 to 1.7

**Comment by X17** [comment]
we are migrating the project from sqlite to mysql. while using python manage.py migrate

> Migrating forwards to 0003_auto__del_field_follow_deleted_at__add_field_follow_created_at.

> core:0001_initial

>AttributeError: 'module' object has no attribute 'ProgrammingError'
